env:
  browser: true
  es2021: true
  node: true
extends: 
  - plugin:@typescript-eslint/recommended
  - standard-with-typescript
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  'no-void': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-invalid-void-type': 'off'
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/no-unsafe-declaration-merging': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/method-signature-style': 'off'
  '@typescript-eslint/no-confusing-void-expression': 'off'
  '@typescript-eslint/no-explicit-any':
    - 'error'
    - ignoreRestArgs: true
